resources:
  'entity:node':
    GET:
      supported_formats:
        - hal_json
        - json
      supported_auth:
        - cookie
  'entity:taxonomy_term':
    GET:
      supported_formats:
        - hal_json
        - json
      supported_auth:
        - cookie
  'entity:file':
    GET:
      supported_formats:
        - hal_json
        - json
      supported_auth:
        - cookie
link_domain: null
